/// Flutter icons Esentis
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'Esentis';

  static const IconData tmdb = IconData(0xe800, fontFamily: _kFontFam);
}
